### ISSUE TITLE
error when following README example

### ISSUE THREAD

**Issue by maxlazarus** [darthbatman/yahoo-stock-prices#1]
the line in the example:
```javascript
var yahooStockPrices = require('../yahoo-stock-prices.js');
```
should be the following if installed with npm:
```javascript
var yahooStockPrices = require('yahoo-stock-prices');
```

**Comment by darthbatman** [comment]
Thank you.
Changes have been reflected in NPM version 1.0.1

**Comment by tqj5047** [comment]
Hi, I did the above import, and try to call the function as shown in readme, however, it keeps giving me Module not found: Error: Can't resolve 'fs' in '/filepath.../node_modules/request/lib'. Do you know what is wrong with it? also I tried npm i request to fix it but no luck.
