### ISSUE TITLE
Return wrong stock price

### ISSUE THREAD

**Issue by phamleduy04** [darthbatman/yahoo-stock-prices#6]
```javascript
var yahooStockPrices = require('yahoo-stock-prices');

function main(){
    yahooStockPrices.getCurrentPrice('AMZN', function(err, price){

        console.log(price);

    });
}
main(); //return 2 but the price at now about 2k
```

**Comment by cluzier** [comment]
I noticed this too for $tsla, is there a fix? Also I am running this one a discord bot and when i search for spy (and some others) it crashes with this error:

```
var price = parseFloat(body.split("currentPrice")[1].split("fmt\":\"")[1].split("\"")[0]);
                            ^

TypeError: body.split is not a function```

**Comment by stefenphelps** [comment]
@cluzier remove the parseFloat and it will return the correct price as a string.

**Comment by rajataudichya** [comment]
There are few indexes that have a  "^" in their symbol, for example "^NSEI", ^BSESN, ^DJI, when these indexes are called similar error is shown var price = parseFloat(body.split("currentPrice")[1].split("fmt\":\"")[1].split("\"")[0]);
